11-MVC/4-Lab-4/LabFive/Models/ErrorViewModel.cs
namespace LabFive.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

11-MVC/4-Lab-4/LabFive/Areas/Admin/Controllers/AshrafController.cs
using Microsoft.AspNetCore.Mvc;

namespace LabFivePL.Areas.Ashraf.Controllers
{
    public class AshrafController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

11-MVC/4-Lab-4/LabFive/Areas/Finance/Controllers/HelloController.cs
using Microsoft.AspNetCore.Mvc;

namespace LabFivePL.Areas.Hello.Controllers
{
    public class HelloController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

11-MVC/4-Lab-4/LabFive/Areas/HR/Controllers/EmployeeController.cs
using BLL.Feature.Interface;
using BLL.Feature.Repository;
using BLL.ModelVM;
using DAL.Context;
using DAL.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace _5_Lab_5.Areas.HR.Controllers
{
    public class EmployeeController : Controller
    {
        IEmployee Employee = new EmployeeRepo();
        //private readonly ApplicationDbContext _context = new ();

        // GET: EmployeeController
        public ActionResult ShowAllEmployees()
        {
            var employees = Employee.GetAllEmployees();
            return View("ShowAllEmployees", employees);
        }

        // GET: EmployeeController/Details/5
        public ActionResult Details(int id)
        {
            var employee = Employee.GetEmployeeById(id);
            return View("Details", employee);
        }

        // GET: EmployeeController/Create
        public ActionResult Create()
        {

            var employeeVM = new EmployeeVM()
            {
                Departments = Employee.GetAllDepartments(),
            };
            return View("Create", employeeVM);
        }

        // POST: EmployeeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(EmployeeVM employee)
        {
            try
            {

                var employeeEntity = new Employee()
                {
                    Name = employee.Name,
                    Email = employee.Email,
                    joinDate = employee.joinDate,
                    phoneNum = employee.phoneNum,
                    Salary = employee.Salary,
                    Password = employee.Password,
                    DepartmentId = employee.DeptId,
                    Department = employee.Department,

                };

                Employee.AddEmployee(employeeEntity);

                return RedirectToAction(nameof(ShowAllEmployees));
            }
            catch
            {
                return View();
            }
        }

        // GET: EmployeeController/Edit/5

        public IActionResult Edit(int id)
        {
            if (id == null)
                return BadRequest();

            var employee = Employee.GetEmployeeById(id);

            if (employee == null)
                return NotFound();

            var employeeVM = new EmployeeVM()
            {
                Id = employee.Id,
                Name = employee.Name,
                Email = employee.Email,
                joinDate = employee.joinDate,
                Password = employee.Password,
                Salary = employee.Salary,
                phoneNum = employee.phoneNum,
                Department = employee.Department,
                DeptId = employee.DeptId,
                Departments = Employee.GetAllDepartments(),
            };

            return View("Edit", employeeVM);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(EmployeeVM employeeVM)
        {
            try
            {
                var employee = new Employee()
                {
                    Id = employeeVM.Id,
                    Name = employeeVM.Name,
                    Email = employeeVM.Email,
                    Department = employeeVM.Department,
                    DepartmentId = employeeVM.DeptId,
                    joinDate = employeeVM.joinDate,
                    Password = employeeVM.Password,
                    phoneNum = employeeVM.phoneNum,
                    Salary = employeeVM.Salary,

                };
                Employee.UpdateEmployee(employee);
                return RedirectToAction(nameof(ShowAllEmployees));
            }
            catch
            {
                return View(employeeVM);
            }

        }


       

        //// POST: EmployeeController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        public IActionResult Delete(int id)
        {
            var employee = Employee.GetById(id);

           

            if (employee is not null)
                Employee.DeleteEmployee(employee);
            return RedirectToAction(nameof(ShowAllEmployees));
        }


    }
}

11-MVC/4-Lab-4/LabFive/Areas/Welcom/Controllers/TestController.cs
using Microsoft.AspNetCore.Mvc;

namespace LabFivePL.Areas.Welcom.Controllers
{
    public class TestController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

11-MVC/4-Lab-4/LabFive/Controllers/HomeController.cs
using LabFive.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LabFive.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

11-MVC/4-Lab-4/LabFive/Areas/Admin/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h1>Index</h1>

11-MVC/4-Lab-4/LabFive/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

11-MVC/4-Lab-4/LabFive/Areas/Finance/Views/Finance/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h1>Index</h1>

11-MVC/4-Lab-4/LabFive/Areas/Welcom/Views/Test/Index.cshtml
@{
    ViewData["Title"] = "Index";

}

<h1>Test Index</h1>

11-MVC/4-Lab-4/LabFive/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employee</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.0/css/dataTables.dataTables.css" />
    <link rel="stylesheet" href="/DataTables/datatables.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" integrity="sha384-4LISF5TTJX/fLmGSxO53rV4miRxdg84mZsxmO8Rx5jGtp/LbrixFETvWa5a6sESd" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC2.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
 
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;500&display=swap" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
S                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area ="HR" asp-controller="Employee" asp-action="ShowAllEmployees">
                             Employees
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Welcom" asp-controller="Test" asp-action="Index">Test</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Finance" asp-controller="Hello" asp-action="Index">Finance</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">

        <main role="main" class="pb-3">

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/2.0.0/js/dataTables.js"></script>
    <script src="/DataTables/datatables.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("JS", required: false)
</body>
</html>